chore: update README.md
cnu-bot/cnubot-server-spring pull request #27
Opened 2022-12-06 08:50 UTC by kingseungwooya

# Describe your changes

ReadMe File 생성 
추가 목록 
- Project name 
- Project Description
- Milestone, Issues, PullRequest 
- Stacks
- Commit Convention
- Project File Tree ( Architecture )
- Contributing
- Contact
- Contributiors
## Issue ticket number and link (optional)
#18 

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2022-12-06 23:15 UTC, ChanhyukPark-Tech requested changes
thx

2022-12-06 23:15 UTC, ChanhyukPark-Tech commented on README.md
> +    <!-- · -->
혹시 필요한 주석인가요?!
불필요한 주석이라면 삭제 부탁드리겠습니다!

2022-12-06 23:15 UTC, ChanhyukPark-Tech commented on README.md
> +<img src="https://img.shields.io/badge/Amazon Ec2-FF9900?style=for-the-badge&logo=Amazon Ec2&logoColor=white">
ec2가 데이터 베이스 범주에 있어도 괜찮을까요?

2022-12-06 23:15 UTC, ChanhyukPark-Tech commented on README.md
> +3. Create your Feature Branch (`git checkout -b feat: create domain`) we have our convention
```suggestion
3. Create your Feature Branch (`git checkout -b feat: create-domain`) we have our convention
```

is better 💪

2022-12-06 23:15 UTC, ChanhyukPark-Tech commented on README.md
> +3. Create your Feature Branch (`git checkout -b feat: create domain`) we have our convention
대소문자 통일 부탁드립니다!

2022-12-07 03:44 UTC, kingseungwooya commented on README.md
> +<img src="https://img.shields.io/badge/Amazon Ec2-FF9900?style=for-the-badge&logo=Amazon Ec2&logoColor=white">
Rds가 ec2 객체 밑에 있다고 생각했는데 클라우드로 생각하는게 맞겠죠?

2022-12-07 03:44 UTC, kingseungwooya commented on README.md
> +3. Create your Feature Branch (`git checkout -b feat: create domain`) we have our convention
알겠습니다!!!!

2022-12-07 03:45 UTC, kingseungwooya commented
Thx for hard review 🥹

2022-12-07 04:13 UTC, ChanhyukPark-Tech commented on README.md
> +<img src="https://img.shields.io/badge/Amazon Ec2-FF9900?style=for-the-badge&logo=Amazon Ec2&logoColor=white">
저희는 rds사용하지않습니다..!

ec2는 infra영역에 해당하는것같네요

2022-12-07 06:14 UTC, kingseungwooya commented on README.md
> +<img src="https://img.shields.io/badge/Amazon Ec2-FF9900?style=for-the-badge&logo=Amazon Ec2&logoColor=white">
그렇군요 알겠습니다! 반영해서 수정하겠습니다!

2022-12-07 09:24 UTC, merged